version: '3.8'

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
services:
  fid_backup:
    build:
      context: ./docker/fid_backup
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    container_name: fid_backup
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./docker/fid_backup/pgbackrest/pgbackrest.conf:/etc/pgbackrest/pgbackrest.conf
      - ./docker/db_dump:/docker-entrypoint-initdb.d
      - ./volume/data/fid:/var/lib/postgresql/data
      - ./volume/data/pgbackrest:/var/lib/pgbackrest
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend